name: progessloadingbutton
description: is a Flutter package with a simple implementation of an animated loading button, complete with success animations.
version: 0.0.1
homepage: https://github.com/letienkhang/progessloadingbutton
repository: https://github.com/letienkhang/progessloadingbutton

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  rename: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
    - assets/images/
